"""Add Event model

Revision ID: 565419907b71
Revises: 
Create Date: 2025-07-28 14:29:12.567526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565419907b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
